name: Release docker image

on:
  release:
    types: [published]

jobs:

  build:
    name: Build and run daeploy Manager
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: va-integrator
        password: ${{ secrets.VA_GITHUB_TOKEN }}

    - name: Docker build and push
      run: |
        docker build --build-arg version=${{ github.event.release.tag_name }} -t ghcr.io/vikinganalytics/mvi/daeploy_manager:${{ github.event.release.tag_name }} .
        docker push ghcr.io/vikinganalytics/mvi/daeploy_manager:${{ github.event.release.tag_name }}


         
      
