name: Release docker image

on:
  release:
    types: [published]

jobs:

  build:
    name: Build and run daeploy Manager
    runs-on: [self-hosted, ubuntu, ibm]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DAEPLOY_DOCKER_USERNAME }}
        password: ${{ secrets.DAEPLOY_DOCKER_PASSWORD }}

    - name: Docker build and push
      run: |
        docker build --build-arg version=${{ github.event.release.tag_name }} -t daeploy/manager:${{ github.event.release.tag_name }} -t daeploy/manager:latest .
        docker push --all-tags daeploy/manager
