name: Provision Daeploy Manager

on:
  workflow_dispatch:
    inputs:
      host_name:
        description: 'Host name of server'     
        required: true
        default: 'demo.nodes.daeploy.com'
      version:
        description: 'Version to be provisioned'
        required: true
        default: 'latest'
      secured:
        description: 'Use HTTPS (SSL), -H for yes, empty for no'
        required: false
        default: ''
      admin_password:
        description: 'Password for admin user'
        required: true
        default: 'admin'
      extra_options:
        description: 'Extra options to pass to start_manager'
        required: false
        default: ''


jobs:

  provision:
    name: Provision a new docker container
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy BASH script via ssh 
      uses: appleboy/scp-action@master
      with:
        host: ${{ github.event.inputs.host_name }}
        username: manager
        key: ${{ secrets.MANAGER_SSH_KEY }}
        port: 22
        source: "start_manager"
        target: "."
      
    - name: Login to DockerHub account and start a daeploy Manager
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ github.event.inputs.host_name }}
        SECURED: ${{ github.event.inputs.secured }}
        VERSION: ${{ github.event.inputs.version }}
        ADMIN_PASSWORD: ${{ github.event.inputs.admin_password }}
        EXTRA_OPTIONS: ${{ github.event.inputs.extra_options }}
      with:
        host: ${{ github.event.inputs.host_name }}
        username: manager
        key: ${{ secrets.MANAGER_SSH_KEY }}
        port: 22
        envs: HOST,SECURED,VERSION,ADMIN_PASSWORD
        script: bash start_manager -n $HOST $SECURED -v $VERSION -w $ADMIN_PASSWORD -A $EXTRA_OPTIONS